### PR TITLE
Add VAT validation to billing address

### LINKED ISSUE #3: Vat number is not validated on the billing address
### Steps to reproduce
1. Uncheck 'My billing and shipping address are the same'
2. Fill in the vat number

### Expected result
The vat number will be validated on the billing address

### Actual result
The vat number is not validated on the billing address

### PR DESCRIPTION
**Pull request by thijsdewitt**
Fixes #3

### CODE REVIEW

**Comment by thijsdewitt** [comment]
Since it is't only validating the shipping address anymore, would you like to rename the `ShipppingAddressModifiers` class as well?

**Comment by Tjitse-E** [comment]
> Since it is't only validating the shipping address anymore, would you like to rename the `ShipppingAddressModifiers` class as well?

Yeah let's do that!

**Review by Tjitse-E — CHANGES_REQUESTED** [review]
See https://github.com/Vendic/hyva-checkout-geissweb-euvat/pull/4#issuecomment-1761180578

**Comment by Tjitse-E** [comment]
@thijsdewitt  as discussed via slack I will close this PR, since it could lead to invalid behaviour (a customer could get VAT exempt if the billing address is correctly validated, but the shipping country is equal to the merchant country). 

Thanks for your pull request!

**Pull request closed without merging**
